name = "Universal"
license = "MIT"
licenselink = "https://github.com/devcows/hugo-universal-theme/blob/master/LICENSE"
description = "A port of the Universal theme"
homepage = "//github.com/devcows/hugo-universal-theme"
tags = ["article", "company", "portfolio", "projects", "minimal", "responsive"]
features = ["article", "themes", "disqus", "minimal", "responsive","vocabulary"]
min_version = 0.15

[author]
    name = "adrianmo"
    homepage = "//github.com/adrianmo"

# If Porting existing theme
[original]
    author =  "bootstrapious"
    homepage = "http://bootstrapious.com/p/universal-business-e-commerce-template"
