---
title: paleoData_proxy
categories: [vocabulary]
summary: Physical, chemical, and/or biological systems or components that react to environmental or climatic conditions, and imprint onto the archive.
---


# paleoData_proxy

Physical, chemical, and/or biological systems or components that react to environmental or climatic conditions, and imprint onto the archive.


---



### [10Be](#10Be){#10Be}


#### Definition
the concentration of a radioactive isotope of beryllium that has 6 neutrons and 4 protons and that is used to reconstruct solar activity and to date ice cores.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">10Be</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=835) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=835)


---



### [accumulation rate](#accumulation_rate){#accumulation_rate}


#### Definition
TBD


*source: TBD*


#### Known synonyms
sed accumulation


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [ACL](#ACL){#ACL}


#### Definition
a chain length index that is the average number of carbon atoms within organic compound chains in a sample.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">average chain length</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4170) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4170)


---



### [Al2O3](#Al2O3){#Al2O3}


#### Definition
an inorganic compound that has the chemical formula Al2O3.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">aluminum oxide</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=305) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=305)


---



### [Al/Si](#Al_Si){#Al_Si}


#### Definition
TBD


*source: TBD*


#### Known synonyms
AlSi


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [alkenone](#alkenone){#alkenone}


#### Definition
a ketone that is a long-chain unsaturated methyl and ethyl n-ketone produced by a few phytoplankton species of the class Prymnesiophyceae (Credit: Wikipedia).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">alkenone</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2485) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2485)


---



### [amoeba](#amoeba){#amoeba}


#### Definition
an identifiable organism that is an ameboid protist with a test and that belongs to the kingdom Protozoa. Traditionally, those species that form large networks of anastomosing pseudopodia, despite of some of them having tests e.g. Foraminifera, are not counted amongst testate amoebae (Credit: Wikipedia).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">testate amoeba</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3577) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3577)


---



### [Ba/Al](#Ba_Al){#Ba_Al}


#### Definition
the elemental ratio of barium to aluminum.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">barium/aluminum</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2410) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2410)


---



### [Ba/Ca](#Ba_Ca){#Ba_Ca}


#### Definition
the elemental ratio of barium to calcium.


*source: PaST*


#### Known synonyms
BaCa


#### NOAA PaST Thesaurus term
[<font size="4">barium/calcium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=317) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=317)


---



### [Ba/Sr](#Ba_Sr){#Ba_Sr}


#### Definition
TBD


*source: TBD*


#### Known synonyms



#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [biomarker](#biomarker){#biomarker}


#### Definition
TBD


*source: TBD*


#### Known synonyms
C15 fatty alcohols, C37.concentration


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [BIT](#BIT){#BIT}


#### Definition
an organic compound index that is the abundance of branched tetraethers relative to isoprenoid tetraethers, indicative of the relative amounts of soil organic matter and aquatic organic matter.


*source: PaST*


#### Known synonyms
BITindex


#### NOAA PaST Thesaurus term
[<font size="4">branched and isoprenoid tetraether index</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1676) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1676)


---



### [borehole](#borehole){#borehole}


#### Definition
a data type that consists of direct measurements of subsurface temperature from boreholes drilled into materials such as rock and glacier ice.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">borehole</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=114) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=114)


---



### [BSi](#BSi){#BSi}


#### Definition
a hydrated, amorphous form of silicon dioxide with the formula SiO2•nH20 that is biogenically precipitated by a variety of organisms including chrysophytes, diatoms, radiolarians, silicoflagellates, and sponges (Credit: Last et al. 2001 Tracking Environmental Change Using Lake Sediments).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">biogenic silica</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4018) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4018)


---



### [bubble frequency](#bubble_frequency){#bubble_frequency}


#### Definition
TBD


*source: TBD*


#### Known synonyms



#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [bulk density](#bulk_density){#bulk_density}


#### Definition
TBD


*source: TBD*


#### Known synonyms
gamma


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [bulk sediment](#bulk_sediment){#bulk_sediment}


#### Definition
sediment from which all water has been removed.


*source: PaST*


#### Known synonyms
BulkSed


#### NOAA PaST Thesaurus term
[<font size="4">dry sediment</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1502) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1502)


---



### [C/N](#C_N){#C_N}


#### Definition
the elemental ratio of carbon to nitrogen.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">carbon/nitrogen</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=750) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=750)


---



### [Ca/K](#Ca_K){#Ca_K}


#### Definition
the elemental ratio of calcium to potassium.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">calcium/potassium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3783) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3783)


---



### [Ca/Ti](#Ca_Ti){#Ca_Ti}


#### Definition
the elemental ratio of calcium to titanium.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">calcium/titanium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1635) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1635)


---



### [Ca/Mg](#Ca_Mg){#Ca_Mg}


#### Definition
TBD


*source: TBD*


#### Known synonyms



#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [CaCO3](#CaCO3){#CaCO3}


#### Definition
a carbonate with the chemical formula CaCO3 but of unspecified crystal structure.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">calcium carbonate</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1515) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1515)


---



### [calcification rate](#calcification_rate){#calcification_rate}


#### Definition
a formation rate that is a rate of skeletal growth in calcifying organisms, often expressed as a mass times unit area per time (e.g., g cm2/yr)


*source: PaST*


#### Known synonyms
calcification


#### NOAA PaST Thesaurus term
[<font size="4">calcification rate</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=756) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=756)


---



### [calcite](#calcite){#calcite}


#### Definition
a calcium carbonate with rhombohedral crystal structure.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">calcite</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=482) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=482)


---



### [carbonate](#carbonate){#carbonate}


#### Definition
an identified mineral characterized by a fundamental anionic structure of CO3(2-) (Credit: Dictionary of Geological Terms).


*source: PaST*


#### Known synonyms
authigenic carbonate, Carbonate content


#### NOAA PaST Thesaurus term
[<font size="4">carbonate</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=692) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=692)


---



### [cellulose](#cellulose){#cellulose}


#### Definition
an organooxygen compound with the general formula (C6H10O5)n and that is an important structural component of the cell walls of green plants.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">cellulose</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=689) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=689)


---



### [charcoal](#charcoal){#charcoal}


#### Definition
a bulk biological material that consists of any black-colored plant-derived material that has had its chemical composition and structure altered as a result of heating in a fire, and retains recognizable anatomic structure of the plant material, even if only in a fragmentary form (Credit: Smol et al. 2001 Tracking Environmental Change Using Lake Sediments).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">charcoal</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=630) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=630)


---



### [chironomid](#chironomid){#chironomid}


#### Definition
an identifiable organism that belongs to one of several families in the kingdom Animalia, phylum Arthropoda, class Insecta, order Diptera.


*source: PaST*


#### Known synonyms
Chironomid, midge


#### NOAA PaST Thesaurus term
[<font size="4">midge</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1571) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1571)


---



### [chlorophyll](#chlorophyll){#chlorophyll}


#### Definition
an organic pigment that is any of several green pigments found in cyanobacteria and the chloroplasts of algae and plants and that is composed of carbon, hydrogen, oxygen, nitrogen, and magnesium.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">chlorophyll</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1615) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1615)


---



### [chrysophyte assemblage](#chrysophyte_assemblage){#chrysophyte_assemblage}


#### Definition
an assemblage of golden or golden-brown algae that belong to the kingdom Chromista, class Chrysophyceae.


*source: PaST*


#### Known synonyms
chrysophyte


#### NOAA PaST Thesaurus term
[<font size="4">chrysophyte assemblage</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4080) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4080)


---



### [cladoceran](#cladoceran){#cladoceran}


#### Definition
an identifiable organism commonly known as a water flea that belongs to the kingdom Animalia, phylum Arthropoda, class Branchiopoda, order Cladocera.


*source: PaST*


#### Known synonyms
Cladocera


#### NOAA PaST Thesaurus term
[<font size="4">cladoceran</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3587) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3587)


---



### [coccolithophore](#coccolithophore){#coccolithophore}


#### Definition
an identifiable organism that is a unicellular phytoplankton and that belongs to the kingdom Chromista, phylum Haptophyta, class Prymnesiophyceae.


*source: PaST*


#### Known synonyms
coccolith


#### NOAA PaST Thesaurus term
[<font size="4">coccolithophore</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3250) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3250)


---



### [d13C](#d13C){#d13C}


#### Definition
the ratio of two isotopes of carbon, 13C/12C, in a sample compared to that of a standard, typically the Pee Dee Belemnite, as in: ((13C/12C sample)/(13C/12C standard) - 1) x 1000.


*source: PaST*


#### Known synonyms
d13Cwax


#### NOAA PaST Thesaurus term
[<font size="4">delta 13C</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=320) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=320)


---



### [d15N](#d15N){#d15N}


#### Definition
the ratio of two isotopes of nitrogen, 15N/14N, in a sample compared to that of a standard, typically modern air ratios, as in: ((15N/14N sample)/(15N/14N standard) - 1) x 1000.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">delta 15N</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=322) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=322)


---



### [d15N/d40Ar](#d15N_d40Ar){#d15N_d40Ar}


#### Definition
TBD


*source: TBD*


#### Known synonyms
15N/40Ar fractionation, d15Nd40Ar


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [d18O](#d18O){#d18O}


#### Definition
the ratio of two isotopes of oxygen, 18O/16O, in a sample compared to that of a standard, typically either Pee Dee Belemnite or standard mean ocean water, as in: ((18O/16O sample)/(18O/16O standard) - 1) x 1000.


*source: PaST*


#### Known synonyms
cellulose d18O, delta18O, foram d18O


#### NOAA PaST Thesaurus term
[<font size="4">delta 18O</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=323) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=323)


---



### [dD](#dD){#dD}


#### Definition
the ratio of two isotopes of hydrogen, 2H/1H, in a sample compared to that of a standard, typically standard mean ocean water, as in: ((2H/1H sample)/(2H/1H standard) - 1) x 1000.


*source: PaST*


#### Known synonyms
d2H, dDwax, leaf wax, LeafWax, leafWax


#### NOAA PaST Thesaurus term
[<font size="4">delta 2H</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=324) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=324)


---



### [deuterium excess](#deuterium_excess){#deuterium_excess}


#### Definition
a measure of how different a delta 2H value is from the value expected from the Global Meteoric Water Line, that is delta 2H - 8* delta 18O.


*source: PaST*


#### Known synonyms
deterium excess, dx


#### NOAA PaST Thesaurus term
[<font size="4">deuterium excess</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1426) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1426)


---



### [diatom](#diatom){#diatom}


#### Definition
an identifiable organism that is a unicellular phytoplankton and that belongs to the kingdom Chromista, phylum Ochrophyta, class Bacillariophyceae.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">diatom</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1601) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1601)


---



### [dinocyst](#dinocyst){#dinocyst}


#### Definition
an identifiable organism that belongs to the kingdom Chromista, division Pyrrophycophyta.


*source: PaST*


#### Known synonyms
dynocist MAT


#### NOAA PaST Thesaurus term
[<font size="4">dinoflagellate</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4532) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4532)


---



### [dry bulk density](#dry_bulk_density){#dry_bulk_density}


#### Definition
TBD


*source: TBD*


#### Known synonyms
DBD


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [Eu/Zr](#Eu_Zr){#Eu_Zr}


#### Definition
TBD


*source: TBD*


#### Known synonyms



#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [Fe](#Fe){#Fe}


#### Definition
a chemical element with atomic number 26.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">iron</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=285) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=285)


---



### [Fe/Al](#Fe_Al){#Fe_Al}


#### Definition
the elemental ratio of iron to aluminum.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">iron/aluminum</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2416) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2416)


---



### [Fe/Ca](#Fe_Ca){#Fe_Ca}


#### Definition
TBD


*source: TBD*


#### Known synonyms
FeCa


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [Fe/K](#Fe_K){#Fe_K}


#### Definition
the elemental ratio of iron to potassium.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">iron/potassium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3785) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3785)


---



### [Fe/Mn](#Fe_Mn){#Fe_Mn}


#### Definition
the elemental ratio of iron to manganese.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">iron/manganese</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1638) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1638)


---



### [foraminifera](#foraminifera){#foraminifera}


#### Definition
an identifiable organism that belongs to the kingdom Protozoa, order Foraminiferida.


*source: PaST*


#### Known synonyms
benthic foraminifers, foraminifer, N. dutertrei, planktonic foraminifera, planktonic foraminifera, transfer function, Uvigerina mediterranea, G. bulloides


#### NOAA PaST Thesaurus term
[<font size="4">foraminifer</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2500) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2500)


---



### [GDGT](#GDGT){#GDGT}


#### Definition
an ether that is a tetraether membrane lipid and that contains between 0 and 4 cyclopentane moieties, with an increasing number of cyclopentane moieties related to the temperature of formation.


*source: PaST*


#### Known synonyms
brGDGT


#### NOAA PaST Thesaurus term
[<font size="4">glycerol dialkyl glycerol tetraether</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1680) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1680)


---



### [grain size](#grain_size){#grain_size}


#### Definition
the diameter of individual grains of a material such as sediment, dust, or ice.


*source: PaST*


#### Known synonyms
particle size


#### NOAA PaST Thesaurus term
[<font size="4">grain size</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1233) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1233)


---



### [HBI](#HBI){#HBI}


#### Definition
an alkene that is highly-branched and composed of a number of isoprene (C5H8) units and that is produced by a relatively small number of marine and freshwater diatoms belonging to the Haslea, Navicula, Pleurosigma, and Rhizosolenia genera (Credit: Belt et al. 2013, 10.1016/j.quascirev.2012.12.001).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">highly-branched isoprenoid alkene</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2283) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2283)


---



### [historical](#historical){#historical}


#### Definition
a data type that includes measurements of past climatic conditions and climate-dependent phenomena as observed and recorded by humans not using modern meteorological instruments.


*source: PaST*


#### Known synonyms
Documentary, historic


#### NOAA PaST Thesaurus term
[<font size="4">historical</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3460) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3460)


---



### [humification](#humification){#humification}


#### Definition
a measure of the extent to which a peat sample has undergone decomposition and humic acids have been produced.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">humification index</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2129) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2129)


---



### [ice accumulation](#ice_accumulation){#ice_accumulation}


#### Definition
TBD


*source: TBD*


#### Known synonyms
Ice Accumulation


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [ice melt](#ice_melt){#ice_melt}


#### Definition
the ice mass loss from a glacier, ice-cap, ice-sheet, or ice-shelf through phase transformation to liquid water.


*source: PaST*


#### Known synonyms
melt, melt layer


#### NOAA PaST Thesaurus term
[<font size="4">ice melt</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4951) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4951)


---



### [inorganic carbon](#inorganic_carbon){#inorganic_carbon}


#### Definition
carbon that is derived from an inorganic source.


*source: PaST*


#### Known synonyms
TIC


#### NOAA PaST Thesaurus term
[<font size="4">inorganic carbon</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=996) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=996)


---



### [IP25](#IP25){#IP25}


#### Definition
a highly-branched isoprenoid alkene that contains 25 carbon atoms and that is produced selectively by sea ice diatoms (Credit: Belt et al. 2013, 10.1016/j.quascirev.2012.12.001).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">ice proxy with 25 carbon atoms</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2493) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2493)


---



### [K/Al](#K_Al){#K_Al}


#### Definition
the elemental ratio of potassium to aluminum.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">potassium/aluminum</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2422) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2422)


---



### [lake level](#lake_level){#lake_level}


#### Definition
a geographic variable that quantifies the height of the lake water surface relative to some datum.


*source: PaST*


#### Known synonyms
Lake stratigraphy and radiocarbon dating of macrofossils, lakeLevel, lakelevel, LakeStatus


#### NOAA PaST Thesaurus term
[<font size="4">lake level</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2137) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2137)


---



### [latewood cellulose](#latewood_cellulose){#latewood_cellulose}


#### Definition
cellulose from wood that formed late in the growing season and that tends to consist of small and thick-walled cells.


*source: PaST*


#### Known synonyms
late-wood cellulose


#### NOAA PaST Thesaurus term
[<font size="4">latewood cellulose</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1589) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1589)


---



### [LDI](#LDI){#LDI}


#### Definition
an organic compound index calculated based on the relative abundance of long chain alkyl 1,13- and 1,15-diols.


*source: PaST*


#### Known synonyms
long chain diol


#### NOAA PaST Thesaurus term
[<font size="4">long-chain diol index</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=5705) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=5705)


---



### [macrofossils](#macrofossils){#macrofossils}


#### Definition
a data type that includes measurements of plant remains large enough to be observed without a microscope.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">plant macrofossils</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4595) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4595)


---



### [magnetic](#magnetic){#magnetic}


#### Definition
TBD


*source: TBD*


#### Known synonyms
ARM/IRM, IRM


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [magnetic susceptibility](#magnetic_susceptibility){#magnetic_susceptibility}


#### Definition
a magnetic moment that is the degree to which a material can be magnetized in an external magnetic field.


*source: PaST*


#### Known synonyms
Magnetic Susceptibility, MS


#### NOAA PaST Thesaurus term
[<font size="4">magnetic susceptibility</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1793) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1793)


---



### [mass accumulation rate](#mass_accumulation_rate){#mass_accumulation_rate}


#### Definition
a rate unit that is a standard measure of the accumulation or flow of mass per unit area per time.


*source: PaST*


#### Known synonyms
MAR


#### NOAA PaST Thesaurus term
[<font size="4">mass per area per time unit</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4704) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4704)


---



### [maximum latewood density](#maximum_latewood_density){#maximum_latewood_density}


#### Definition
the density of xylem cells in wood that formed near the end of the growing season and that tend to be small and thick-walled.


*source: PaST*


#### Known synonyms
delta Density, MXD


#### NOAA PaST Thesaurus term
[<font size="4">latewood density</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1573) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1573)


---



### [Mg](#Mg){#Mg}


#### Definition
a chemical element with atomic number 12.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">magnesium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=891) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=891)


---



### [Mg/Ca](#Mg_Ca){#Mg_Ca}


#### Definition
the elemental ratio of magnesium to calcium.


*source: PaST*


#### Known synonyms
foram Mg/Ca, Foram Mg/Ca, MgCa


#### NOAA PaST Thesaurus term
[<font size="4">magnesium/calcium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=327) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=327)


---



### [Mn/Fe](#Mn_Fe){#Mn_Fe}


#### Definition
the elemental ratio of manganese to iron.


*source: PaST*


#### Known synonyms
MnFe


#### NOAA PaST Thesaurus term
[<font size="4">manganese/iron</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1013) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1013)


---



### [Mn/Ti](#Mn_Ti){#Mn_Ti}


#### Definition
the elemental ratio of manganese to titanium.


*source: PaST*


#### Known synonyms
MnTi


#### NOAA PaST Thesaurus term
[<font size="4">manganese/titanium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1640) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1640)


---



### [multiproxy](#multiproxy){#multiproxy}


#### Definition
a material used to create a climate reconstruction that consists of proxies from more than two proxy data types.


*source: PaST*


#### Known synonyms
Ti,Ca,K, pore ice d2H and d18O, hybrid, Hybrid Grain Size, hybrid-ice, hybrid-lake


#### NOAA PaST Thesaurus term
[<font size="4">multiple proxies</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3630) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3630)


---



### [deleteMe](#deleteMe){#deleteMe}


#### Definition
TBD


*source: TBD*


#### Known synonyms
PCA, ((( calcium carbonate ))) accumulation /// null, 3-OH-Fatty Acids, Age, CAS, coral, element, Element Ratio, ice, isotope, isotope diffusion, MG0, middle-wood cellulose, mineral, mineralogy, percent, sediment, Sediment, TDS, trace element / CA, TraceElement, u Cluster 2


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [CIA](#CIA){#CIA}


#### Definition
TBD


*source: TBD*


#### Known synonyms
Chemical Index of Alteration


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [ostracod](#ostracod){#ostracod}


#### Definition
an identifiable organism that belongs to the kingdom Animalia, phylum Arthropoda, class Ostracoda.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">ostracod</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1002) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1002)


---



### [P-aqueous](#P-aqueous){#P-aqueous}


#### Definition
an organic compound index that measures the relative predominance of submerged versus emergent aquatic plants and that is generally calculated from n-alkanes as (C23 + C25)/(C23 + C25 + C29 + C31).


*source: PaST*


#### Known synonyms
Paq


#### NOAA PaST Thesaurus term
[<font size="4">P-aqueous</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1000103) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1000103)


---



### [peat ash](#peat_ash){#peat_ash}


#### Definition
TBD


*source: TBD*


#### Known synonyms



#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [pH](#pH){#pH}


#### Definition
a measure of acidity that is calculated as the negative logarithm of the hydrogen ion concentration.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">pH</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=569) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=569)


---



### [pollen](#pollen){#pollen}


#### Definition
a bulk biological material that consists of microscopic grains produced by seed plants for reproduction.


*source: PaST*


#### Known synonyms
aquatic palynomorphs


#### NOAA PaST Thesaurus term
[<font size="4">pollen</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=5578) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=5578)


---



### [radiolaria](#radiolaria){#radiolaria}


#### Definition
an identifiable organism that belongs to the kingdom Protozoa, order Radiolaria.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">radiolarian</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2796) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2796)


---



### [Rb](#Rb){#Rb}


#### Definition
a chemical element with atomic number 37.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">rubidium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=913) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=913)


---



### [Rb/Sr](#Rb_Sr){#Rb_Sr}


#### Definition
TBD


*source: TBD*


#### Known synonyms



#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [reflectance](#reflectance){#reflectance}


#### Definition
an electromagnetic property that measures the amount of light that reflects from the surface of a material.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">reflectance</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1005) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1005)


---



### [ring width](#ring_width){#ring_width}


#### Definition
a physical measurement of the width of all or of some subcomponent of one annual ring from a tree.


*source: PaST*


#### Known synonyms
TRW


#### NOAA PaST Thesaurus term
[<font size="4">ring width</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3639) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3639)


---



### [Sr](#Sr){#Sr}


#### Definition
a chemical element with atomic number 38.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">strontium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=290) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=290)


---



### [Sr/Ca](#Sr_Ca){#Sr_Ca}


#### Definition
the elemental ratio of strontium to calcium.


*source: PaST*


#### Known synonyms
Ca/Sr, Coral Sr/Ca, SrCa


#### NOAA PaST Thesaurus term
[<font size="4">strontium/calcium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=328) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=328)


---



### [stratigraphy](#stratigraphy){#stratigraphy}


#### Definition
TBD


*source: TBD*


#### Known synonyms
Minerogenic layers, Plant detrital layers, Stratigraphy


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [sulfur](#sulfur){#sulfur}


#### Definition
a chemical element with atomic number 16.


*source: PaST*


#### Known synonyms
S


#### NOAA PaST Thesaurus term
[<font size="4">sulfur</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=902) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=902)


---



### [TEX86](#TEX86){#TEX86}


#### Definition
an organic compound index that is calculated as the ratio of different isoprenoidal glycerol dialkyl glycerol tetraethers.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">tetraether index of 86 carbon atoms</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1599) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1599)


---



### [Ti](#Ti){#Ti}


#### Definition
a chemical element with atomic number 22.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">titanium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=292) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=292)


---



### [Ti/Al](#Ti_Al){#Ti_Al}


#### Definition
the elemental ratio of titanium to aluminum.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">titanium/aluminum</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3687) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3687)


---



### [Ti/Ca](#Ti_Ca){#Ti_Ca}


#### Definition
the elemental ratio of titanium to calcium.


*source: PaST*


#### Known synonyms
ln(ti/ca), Ti/CA, TiCa


#### NOAA PaST Thesaurus term
[<font size="4">titanium/calcium</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2426) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2426)


---



### [TOC](#TOC){#TOC}


#### Definition
carbon that is derived from an organic source.


*source: PaST*


#### Known synonyms
LOI


#### NOAA PaST Thesaurus term
[<font size="4">organic carbon</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=995) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=995)


---



### [total nitrogen](#total_nitrogen){#total_nitrogen}


#### Definition
TBD


*source: TBD*


#### Known synonyms
TN


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [varve thickness](#varve_thickness){#varve_thickness}


#### Definition
the thickness of a sublayer of or an entire annually-resolved varve in a sediment sequence.


*source: PaST*


#### Known synonyms
varve, Varve, varve property, varves


#### NOAA PaST Thesaurus term
[<font size="4">varve thickness</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1630) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1630)


---

