---
title: paleoData_units
categories: [vocabulary]
summary: The units of a measured or inferred variable at the column level.
---


# paleoData_units

The units of a measured or inferred variable at the column level.


---



### [Am2/yr](#Am2_yr){#Am2_yr}


#### Definition
the remanent magnetization that is acquired without the aid of changes in temperature, generally from the application and subsequent removal of an applied direct current field (Credit: Encyclopedia of Geomagnetism and Paleomagnetism).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">isothermal remanent magnetization</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1085) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1085)


---



### [atomic ratio](#atomic_ratio){#atomic_ratio}


#### Definition
a dimensionless unit that is the ratio of atoms of one kind to atoms of another kind.


*source: PaST*


#### Known synonyms
Atomic ratio


#### NOAA PaST Thesaurus term
[<font size="4">atomic ratio</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=5701) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=5701)


---



### [cgs](#cgs){#cgs}


#### Definition
a dimensionless measure of volume magnetic susceptibility that results from values of magnetization and magnetic field strength in centimeter-gram-second units, i.e., electromagnetic units. The dimensionless cgs value of volume magnetic susceptibility can be multiplied by 4*pi to generate the dimensionless SI value.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">dimensionless (CGS system)</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=631) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=631)


---



### [cm](#cm){#cm}


#### Definition
a length unit which is equal to one hundredth of a meter or 10^[-2] m (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
cmblf


#### NOAA PaST Thesaurus term
[<font size="4">centimeter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=122) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=122)


---



### [cm/kyr](#cm_kyr){#cm_kyr}


#### Definition
a length per time unit that is one hundredth of a meter, or 10^[-2] m, per one thousand years, or 10^[3] years.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">centimeter per kiloyear</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2371) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2371)


---



### [cm/yr](#cm_yr){#cm_yr}


#### Definition
a length per time unit that is one hundredth of a meter, or 10^[-2] m, per one year.


*source: PaST*


#### Known synonyms
cm/a, cm yr-1


#### NOAA PaST Thesaurus term
[<font size="4">centimeter per year</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1713) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1713)


---



### [cm3](#cm3){#cm3}


#### Definition
a volume unit which is equal to one millionth of a cubic meter or 10^[-6] m^[3], or to 1 ml (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">cubic centimeter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1712) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1712)


---



### [count](#count){#count}


#### Definition
a dimensionless unit that denotes a simple count of things (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
number, #, counts, dark_sum, cts


#### NOAA PaST Thesaurus term
[<font size="4">count</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=704) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=704)


---



### [count/century](#count_century){#count_century}


#### Definition
a count per time unit that is a simple count of the occurrence of a substance per one hundred years.


*source: PaST*


#### Known synonyms
envents/100yrs


#### NOAA PaST Thesaurus term
[<font size="4">count per century</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2373) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2373)


---



### [count/cm2](#count_cm2){#count_cm2}


#### Definition
a count per area unit that applies to an area of one square centimeter, or 10^[-4] square meters.


*source: PaST*


#### Known synonyms
number/cm2


#### NOAA PaST Thesaurus term
[<font size="4">count per square centimeter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3814) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3814)


---



### [count/cm2/yr](#count_cm2_yr){#count_cm2_yr}


#### Definition
a count per area per time unit that is a simple count of a substance per one ten-thousandth of a square meter, or 10^[-4] m2, and per one year.


*source: PaST*


#### Known synonyms
grains>255 micron/cm2/yr, no/cm2/yr


#### NOAA PaST Thesaurus term
[<font size="4">count per square centimeter per year</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1715) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1715)


---



### [count/cm3](#count_cm3){#count_cm3}


#### Definition
a count per volume unit that applies to one cubic centimeter, or 10^[-6] cubic meters.


*source: PaST*


#### Known synonyms
bubbles/cm3, #/cm3


#### NOAA PaST Thesaurus term
[<font size="4">count per cubic centimeter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3815) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3815)


---



### [count/g](#count_g){#count_g}


#### Definition
a count per mass unit that applies to one gram.


*source: PaST*


#### Known synonyms
count per gram, grains/g, millions of valves/g dry sed


#### NOAA PaST Thesaurus term
[<font size="4">count per gram</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3796) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3796)


---



### [count/kyr](#count_kyr){#count_kyr}


#### Definition
a count per time unit that is a simple count of a substance per one thousand years, or 10^[3] years.


*source: PaST*


#### Known synonyms
frequency/1000yrs


#### NOAA PaST Thesaurus term
[<font size="4">count per kiloyear</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1000203) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1000203)


---



### [count/mL](#count_mL){#count_mL}


#### Definition
a count per volume unit that applies to one milliliter, or 10^[-3] liters.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">count per milliliter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3801) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3801)


---



### [count/yr](#count_yr){#count_yr}


#### Definition
a count per time unit that is a simple count of the occurrence of a substance per one year.


*source: PaST*


#### Known synonyms
Floods per year, Floods per yr, floods/yr


#### NOAA PaST Thesaurus term
[<font size="4">count per year</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1720) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1720)


---



### [cps](#cps){#cps}


#### Definition
a count per time unit that is a simple count of the occurrence of a substance per one second.


*source: PaST*


#### Known synonyms
count per second


#### NOAA PaST Thesaurus term
[<font size="4">count per second</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1721) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1721)


---



### [day](#day){#day}


#### Definition
a duration unit that is equal to 24 hours.


*source: PaST*


#### Known synonyms
days


#### NOAA PaST Thesaurus term
[<font size="4">day</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=270) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=270)


---



### [degC](#degC){#degC}


#### Definition
a temperature unit which is equal to one kelvin degree. However, they have their zeros at different points. The centigrade scale has its zero at 273.15 K (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
GDD5, ((( null ))) deg C /// degC, degrees, ºC, Deg, GDD, kelvin


#### NOAA PaST Thesaurus term
[<font size="4">degree Celsius</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=29) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=29)


---



### [degree](#degree){#degree}


#### Definition
an angle unit which is equal to 1/360 of a full rotation or 1.7453310^[-2] rad (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
decimal degrees


#### NOAA PaST Thesaurus term
[<font size="4">degree</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1264) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1264)


---



### [fraction](#fraction){#fraction}


#### Definition
a dimensionless unit that relates the part (the numerator) to the whole (the denominator) and that, by definition, ranges from 0 to 1 (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
fractional abundance, fraction 0 to 1, relative abundance


#### NOAA PaST Thesaurus term
[<font size="4">fraction</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3820) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3820)


---



### [g](#g){#g}


#### Definition
a mass unit which is equal to one thousandth of a kilogram or 10^[-3] kg (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">gram</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=258) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=258)


---



### [g/cm/yr](#g_cm_yr){#g_cm_yr}


#### Definition
a mass per length per time unit that is one thousandth of a kilogram, or 10^[-3] kg, per one hundredth of a meter, or 10^[-2] m, per one year.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">gram per centimeter per year</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1000009) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1000009)


---



### [g/cm2](#g_cm2){#g_cm2}


#### Definition
an area density unit which is equal to the mass of an object in grams, or 10^[-3] kilogram, per square centimeter, or 10^[-4] square meters.


*source: PaST*


#### Known synonyms
gcm2, g cm-1


#### NOAA PaST Thesaurus term
[<font size="4">gram per square centimeter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1724) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1724)


---



### [g/cm2/kyr](#g_cm2_kyr){#g_cm2_kyr}


#### Definition
a mass per area per time unit that is one thousandth of a kilogram, or 10^[-3] kg, per one ten-thousandth of a square meter, or 10^[-4] m^[2], per one thousand years.


*source: PaST*


#### Known synonyms
g/cm2/ka


#### NOAA PaST Thesaurus term
[<font size="4">gram per square centimeter per kiloyear</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1725) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1725)


---



### [g/cm2/yr](#g_cm2_yr){#g_cm2_yr}


#### Definition
a mass per area per time unit that is one thousandth of a kilogram, or 10^[-3] kg, per one ten-thousandth of a square meter, or 10^[-4] m^[2], per one year.


*source: PaST*


#### Known synonyms
g/m^2/a, gcm-2yr-1, g.cm-2.a-1, g/cm^2/y, gcm-2a-1


#### NOAA PaST Thesaurus term
[<font size="4">gram per square centimeter per year</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1726) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1726)


---



### [g/cm3](#g_cm3){#g_cm3}


#### Definition
a mass density unit which is equal to mass of an object in grams divided by the volume in cubic centimeters (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
g/cc, g_cm3, grams/cubic cm


#### NOAA PaST Thesaurus term
[<font size="4">gram per cubic centimeter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1727) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1727)


---



### [g/L](#g_L){#g_L}


#### Definition
a mass density unit which is equal to mass of an object in grams divided by the volume in liters (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">gram per liter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3824) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3824)


---



### [g/m2](#g_m2){#g_m2}


#### Definition
an area density unit which is equal to the mass of an object in  grams, or 10^[-3] kg, per square meter.


*source: PaST*


#### Known synonyms
g/m


#### NOAA PaST Thesaurus term
[<font size="4">gram per square meter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4871) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4871)


---



### [g/m2/yr](#g_m2_yr){#g_m2_yr}


#### Definition
a mass per area per time unit that is one thousandth of a kilogram, or 10^[-3] kg, per one square meter, per one year.


*source: PaST*


#### Known synonyms
gm2yr-1


#### NOAA PaST Thesaurus term
[<font size="4">gram per square meter per year</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1729) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1729)


---



### [grayscale](#grayscale){#grayscale}


#### Definition
reflectance that is quantified only according to intensity, or the amount of light, with low values indicating black and high values indicating white.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">grayscale</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=548) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=548)


---



### [kg/m2/yr](#kg_m2_yr){#kg_m2_yr}


#### Definition
a mass per area per time unit that is one kilogram per one square meter, per one year.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">kilogram per square meter per year</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3832) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3832)


---



### [kg/m3](#kg_m3){#kg_m3}


#### Definition
an area density unit which is equal to the mass of an object in kilograms per square meter.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">kilogram per square meter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4874) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4874)


---



### [km2](#km2){#km2}


#### Definition
an area unit which is equal to one million square meters or 10^[6] m^[2].


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">square kilometer</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3804) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3804)


---



### [km3](#km3){#km3}


#### Definition
a volume unit which is equal to one billion cubic meters or 10^[9] m^[3].


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">cubic kilometer</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3835) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3835)


---



### [log(mg/L)](#log(mg_L)){#log(mg_L)}


#### Definition
TBD


*source: TBD*


#### Known synonyms
log mg/L


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [m](#m){#m}


#### Definition
a length unit which is equal to the length of the path traveled by light in vacuum during a time interval of 1/299 792 458 of a second (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
masl


#### NOAA PaST Thesaurus term
[<font size="4">meter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=124) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=124)


---



### [m3/kg](#m3_kg){#m3_kg}


#### Definition
a specific volume unit which is equal to one cubic meter volume occupied by one kilogram of a particular substance (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
m^3 kg^-1, m3kg-1, m3kg1


#### NOAA PaST Thesaurus term
[<font size="4">cubic meter per kilogram</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1734) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1734)


---



### [mg](#mg){#mg}


#### Definition
a mass unit which is equal to one thousandth of a gram or 10^[-3] g (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">milligram</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=637) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=637)


---



### [mg/cm2/yr](#mg_cm2_yr){#mg_cm2_yr}


#### Definition
a mass per area per time unit that is one thousandth of a gram, or 10^[-3] g, per one ten-thousandth of a square meter, or 10^[-4] m^[2], per one year.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">milligram per square centimeter per year</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1738) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1738)


---



### [mg/g](#mg_g){#mg_g}


#### Definition
a mass fraction unit that measures the number of milligrams, or 10^[-3] g, of one subcomponent of a sample relative to one gram of either another subcomponent or of the entire sample.


*source: PaST*


#### Known synonyms
mg g-1, mill/g


#### NOAA PaST Thesaurus term
[<font size="4">milligram per gram</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1739) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1739)


---



### [mg/kg](#mg_kg){#mg_kg}


#### Definition
a mass fraction unit that measures the number of milligrams, or 10^[-6] kg, of one subcomponent of a sample relative to one kilogram of either another subcomponent or of the entire sample.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">milligram per kilogram</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2390) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2390)


---



### [mg/L](#mg_L){#mg_L}


#### Definition
a mass density unit which is equal to mass of an object in milligrams, or 10^[-3] g, divided by the volume in liters (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">milligram per liter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3842) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3842)


---



### [mm](#mm){#mm}


#### Definition
a length unit which is equal to one thousandth of a meter or 10^[-3] m (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
depth_sample


#### NOAA PaST Thesaurus term
[<font size="4">millimeter</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=128) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=128)


---



### [mm/day](#mm_day){#mm_day}


#### Definition
a length per time unit that is one thousandth of a meter, or 10^[-3] m, per one day.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">millimeter per day</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3847) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3847)


---



### [mm/season](#mm_season){#mm_season}


#### Definition
TBD


*source: TBD*


#### Known synonyms



#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [mm/yr](#mm_yr){#mm_yr}


#### Definition
a length per time unit that is one thousandth of a meter, or 10^[-3] m, per one year.


*source: PaST*


#### Known synonyms
mm/a, ((( null ))) mm /// mm/a


#### NOAA PaST Thesaurus term
[<font size="4">millimeter per year</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3849) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3849)


---



### [mmol/mol](#mmol_mol){#mmol_mol}


#### Definition
a mole fraction unit that measures the number of millimoles, or 10^[-3] mole, of one subcomponent of a sample relative to one mole of either another subcomponent or of the entire sample.


*source: PaST*


#### Known synonyms
mmol_mol


#### NOAA PaST Thesaurus term
[<font size="4">millimole per mole</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1745) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1745)


---



### [log(mmol/mol)](#log(mmol_mol)){#log(mmol_mol)}


#### Definition
a mole fraction unit that measures the number of millimoles, or 10^[-3] mole, of one subcomponent of a sample relative to one mole of either another subcomponent or of the entire sample.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">millimole per mole</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1745) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1745)


---



### [months/year](#months_year){#months_year}


#### Definition
TBD


*source: TBD*


#### Known synonyms



#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [needsToBeChanged](#needsToBeChanged){#needsToBeChanged}


#### Definition
TBD


*source: TBD*


#### Known synonyms
1s, a€°, Floods per 30 years, Floods per 30 yrs (200 yr running average), HU, layers/200yrs, [±], 0.5s, 1 sigma, 10-5, 10^-9 Am2/yr, 1sigma, a°, AfAE’A†a€™AfA¢A¢a€sA¬A…A¡AfAE’A¢a‚¬A¡Afa€sA‚Aug/g, unknown, mcm, mwe, 10^[-8] m3/kg, am2kg-1, area, Aug/cm2/ka, gomcm2yr-1, sum, total, cm2yr-1, square mm/cubic cm


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [ng](#ng){#ng}


#### Definition
a mass unit which is equal to one thousandth of one millionth of a gram or 10^[-9] g (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
ng/sample


#### NOAA PaST Thesaurus term
[<font size="4">nanogram</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=954) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=954)


---



### [ng/g](#ng_g){#ng_g}


#### Definition
a mass fraction unit that measures the number of nanograms, or 10^[-9] g, of one subcomponent of a sample relative to one gram of either another subcomponent or of the entire sample.


*source: PaST*


#### Known synonyms
ng/g sed


#### NOAA PaST Thesaurus term
[<font size="4">nanogram per gram</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3900) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3900)


---



### [peak area](#peak_area){#peak_area}


#### Definition
an area unit that is calculated as the area under the curve of a measured spectrum and that generally gives relative information about the abundance of various sample sub-components.


*source: PaST*


#### Known synonyms
pa/kcps


#### NOAA PaST Thesaurus term
[<font size="4">peak area integral</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1754) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1754)


---



### [percent](#percent){#percent}


#### Definition
a concentration unit that denotes numbers as fractions of 100 (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
%, ((( null ))) % /// percent, wt %, % abs, mol%, mole per mole * 100, percentByWeight, Precent


#### NOAA PaST Thesaurus term
[<font size="4">percent</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=145) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=145)


---



### [permil](#permil){#permil}


#### Definition
a parts per thousand unit, often used directly to refer to isotopic ratios and calculated by calculating the ratio of isotopic concentrations in a sample and in a standard, subtracting one and multiplying by one thousand.


*source: PaST*


#### Known synonyms
((( null ))) per mil /// permil, per mil vs PDB, ((( null ))) per mil /// unitless, per mil, per mil (VPDB), per mil vs VPDB, permil (VSMOW), per mil (PDB), permil vs PDB, permil (PDB), permil (SMOW), permil SMOW, permil VSMOW, permil (VPDB), permil VPDB, permil vs VPDB, permil PDB, permil VPDB 1sig, ‰ PDB, per mil VSMOW, ((( null ))) permil /// unitless, +/- permil PDB, +/- permil SMOW, ± permil, per mil VSMOW 1sig, ((( null ))) permil /// per mil, ‰ SMOW, 1000*counts/counts, d18O, PDB, pemil, permil (PBD), permil (SMOW, not PDB!), permil v pdb, permil VMOW, permil VSMOW 1sig, permit, perml


#### NOAA PaST Thesaurus term
[<font size="4">per mil</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=142) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=142)


---



### [pH](#pH){#pH}


#### Definition
a solution property that quantifies the concentration of hydrogen ions.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">acidity</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=773) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=773)


---



### [ppb](#ppb){#ppb}


#### Definition
a parts per notation unit which denotes the amount of a given substance in a total amount of 1,000,000,000 regardless of the units of measure as long as they are the same or 1 part in 10^[9] (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">parts per billion</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=144) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=144)


---



### [ppm](#ppm){#ppm}


#### Definition
a parts per notation unit which denotes the amount of a given substance in a total amount of 1,000,000 regardless of the units of measure used as long as they are the same or 1 part in 10^[6] (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">parts per million</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=143) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=143)


---



### [practical salinity unit](#practical_salinity_unit){#practical_salinity_unit}


#### Definition
a relative unit for the salinity of water that is defined in terms of the ratio of the electrical conductivity of a water sample at 15 degrees Celsius and the pressure of one standard atmosphere, to that of a solution of 32.4356 grams of potassium chloride (KCl) in 1 kilogram of water at the same temperature and pressure. By definition, a ratio that is exactly equal to one corresponds to a practical salinity of 35.


*source: PaST*


#### Known synonyms
psu


#### NOAA PaST Thesaurus term
[<font size="4">practical salinity unit</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3897) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=3897)


---



### [ratio](#ratio){#ratio}


#### Definition
a dimensionless unit that is a ratio of a measurement to some arbitrarily or non-arbitrarily chosen reference value.


*source: PaST*


#### Known synonyms
ratio cps, g/g, (mg/kg)/(mg/kg), cps/cps, grams/dry weight, sediment 130um, ((( null ))) ratio /// unitless, mm/m, mol_mol, mol/mol, R660_670


#### NOAA PaST Thesaurus term
[<font size="4">relative unit</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4144) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4144)


---



### [refelctance](#refelctance){#refelctance}


#### Definition
an electromagnetic property that measures the amount of light that reflects from the surface of a material.


*source: PaST*


#### Known synonyms
reflectance


#### NOAA PaST Thesaurus term
[<font size="4">reflectance</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1005) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1005)


---



### [SI](#SI){#SI}


#### Definition
a dimensionless measure of volume magnetic susceptibility that results from values of magnetization and magnetic field strength in Standard International units, i.e., ampere per meter.


*source: PaST*


#### Known synonyms
10^-6SI, dimensionless (SI), si, SI 10^-5


#### NOAA PaST Thesaurus term
[<font size="4">dimensionless (SI system)</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1251) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1251)


---



### [ug/cm2/yr](#ug_cm2_yr){#ug_cm2_yr}


#### Definition
a mass per area per time unit that is one millionth of a gram, or 10^[-6] g, per one ten-thousandth of a square meter, or 10^[-4] m^[2], per one year.


*source: PaST*


#### Known synonyms
ugcm-2yr-1


#### NOAA PaST Thesaurus term
[<font size="4">microgram per square centimeter per year</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4400) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=4400)


---



### [ug/g](#ug_g){#ug_g}


#### Definition
a mass fraction unit that measures the number of micrograms, or 10^[-6] grams, of one subcomponent of a sample relative to one gram of either another subcomponent or of the entire sample.


*source: PaST*


#### Known synonyms
ug/g dry sediment, ug/g dry sed, ug g-1 dw, microg_g, [ug/g]


#### NOAA PaST Thesaurus term
[<font size="4">microgram per gram</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1740) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1740)


---



### [um](#um){#um}


#### Definition
a length unit which is equal to one millionth of a meter or 10^[-6] m (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">micrometer</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=126) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=126)


---



### [ug](#ug){#ug}


#### Definition
a mass unit which is equal to one millionth of a gram or 10^[-6] g (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">microgram</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=251) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=251)


---



### [umol/mol](#umol_mol){#umol_mol}


#### Definition
a mole fraction unit that measures the number of micromoles, or 10^[-6] mole, of one subcomponent of a sample relative to one mole of either another subcomponent or of the entire sample.


*source: PaST*


#### Known synonyms



#### NOAA PaST Thesaurus term
[<font size="4">micromole per mole</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2407) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=2407)


---



### [unitless](#unitless){#unitless}


#### Definition
a unit that is a standard measure of physical quantity consisting of only a numerical number without any units (Credit: Units of measurement ontology).


*source: PaST*


#### Known synonyms
unitless index, index, type, absorbance units, FTIRS absorbance units, name, UK37, unitless (anomalies), PC, standardized, 0-10


#### NOAA PaST Thesaurus term
[<font size="4">dimensionless</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=622) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=622)


---



### [yr 14C BP](#yr_14C_BP){#yr_14C_BP}


#### Definition
an age unit of years, derived from radiocarbon dating without calibration to actual years, before present with present defined as 1950 Common Era. Times after 1950 CE are expressed as negative values.


*source: PaST*


#### Known synonyms
radiocarbon years BP, 14C yr BP, yr 14C yr BP, bp14C, C14yr BP


#### NOAA PaST Thesaurus term
[<font size="4">radiocarbon year before present</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1288) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1288)


---



### [yr AD](#yr_AD){#yr_AD}


#### Definition
an age unit of years for the Julian and Gregorian calendars relative to the start of the present era. Times prior to the start of the present era are expressed as negative values.


*source: PaST*


#### Known synonyms
yr, CE, AD, year ce, ad/bc, cal yr AD, year A.D., year C.E., year CE, yr  AD, yr ce, yrad/bc


#### NOAA PaST Thesaurus term
[<font size="4">year Common Era</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=132) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=132)


---



### [yr b2k](#yr_b2k){#yr_b2k}


#### Definition
TBD


*source: TBD*


#### Known synonyms
b2000, cal. BP2000, Years before 2k


#### NOAA PaST Thesaurus term
<font size="4">This concept doesn't exist on PaST</font>


---



### [yr BP](#yr_BP){#yr_BP}


#### Definition
an age unit of years, calibrated to actual years if derived from radiocarbon dating, before present with present defined as 1950 Common Era. Times after 1950 CE are expressed as negative values.


*source: PaST*


#### Known synonyms
BP, cal years BP, cal year BP, cal yr BP, year BP, years BP, yr B.P., yrs bp, cal yr B.P., age=1950-year, cal age BP, cal bp, cal yrs BP, yr bo, yr P, Calibrated


#### NOAA PaST Thesaurus term
[<font size="4">calendar year before present</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=133) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=133)


---



### [yr ka](#yr_ka){#yr_ka}


#### Definition
an age unit of 10^[3] years, calibrated to actual years if derived from radiocarbon dating, before present with present defined as 1950 Common Era. Times after 1950 CE are expressed as negative values.


*source: PaST*


#### Known synonyms
ka


#### NOAA PaST Thesaurus term
[<font size="4">calendar kiloyear before present</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1702) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=1702)


---



### [z score](#z_score){#z_score}


#### Definition
a mathematical unit that describes how many standard deviations away from the mean a value is.


*source: PaST*


#### Known synonyms
zscore, SD units, std dev, SD, sd


#### NOAA PaST Thesaurus term
[<font size="4">standard deviation unit</font>](https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=536) (https://www.ncei.noaa.gov/access/paleo-search/cvterms?termId=536)


---

