---
title: "M39008_3.Eynaud.2009"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: bootstrap
    source_code: embed
    orientation: rows
---

```{r setup, include = FALSE}
library(flexdashboard)
library(maptools)
library(tidyverse)
library(purrr)
library(leaflet)
library(plotly)
library(lipdR)
library(dygraphs)
library(geoChronR)
library(lipdverseR)
#read functions
load("../../temp.Rdata")
load("../../chronTemp.Rdata")


#remove columns we don't want to plot
varNames <- sapply(TS, "[[","paleoData_variableName")

# good <- which(!(varNames %in% c("year","depth","age")))
# TS <- TS[good]



#All datasets
dsn <- lipdR::pullTsVariable(TS,"dataSetName")
ui <- which(!duplicated(dsn))
udsn <- dsn[ui]
lat <- lipdR::pullTsVariable(TS,"geo_latitude")[ui]
lon <- lipdR::pullTsVariable(TS,"geo_longitude")[ui]
elev <- lipdR::pullTsVariable(TS,"geo_elevation")[ui]


archiveType <- lipdR::pullTsVariable(TS,"archiveType")[ui]
link <- paste0(udsn,".html") %>%
  str_replace_all("'","_")


#Organize metadata for map
map.meta <- data.frame(dataSetName = udsn, #datasetname
                       lat = lat,#lat
                       lon = lon,#lon
                      # elev = elev,#elevation
                       archiveType = factor(archiveType),#archiveType
                       link = link)#Link


#set index number

i = 370
thisTS <- TS[which(udsn[i] == dsn)]
```
#M39008_3.Eynaud.2009

Metadata {.sidebar}
-------------------------------------
[Download LiPD file](M39008_3.Eynaud.2009.lpd)
            

[Edit LiPD file](http://lipd.net/playground?source=http://lipdverse.org/Temp12k/1_0_2/M39008_3.Eynaud.2009.lpd)
            

[Download paleoData only (csv)](M39008_3.Eynaud.2009.csv)
            

[Download chronData only (csv)](M39008_3.Eynaud.2009-chron.csv)
            

[Report an issue (include dataset name)](https://github.com/nickmckay/LiPDverse/issues)

<details open style="margin-left: 0px">
<summary>root</summary>
<p style="margin-left: 0px"><strong>archiveType: </strong>MarineSediment
<p style="margin-left: 0px"><strong>originalDataUrl: </strong>10.1594/PANGAEA.738148
<p style="margin-left: 0px"><strong>lipdVersion: </strong>1.3
</details>
<details>
<summary>pub</summary>
<details style="margin-left: 10px">
<summary>pub1</summary>
<p style="margin-left: 10px"><strong>author: </strong>list(list(name = "Eynaud, Fr̩d̩rique; de Abreu, L̼cia; Voelker, Antje; Sch̦nfeld, Joachim; Salgueiro, Emilia; Turon, Jean-Louis; Penaud, Aur̩lie; Toucanne, Samuel; Naughton, Filipa; S  nchez Go̱i, Mar _a Fernanda; Malaiz̩, Bruno; Cacho, Isabel"))
<p style="margin-left: 10px"><strong>citeKey: </strong>Z2466U3P
<p style="margin-left: 10px"><strong>journal: </strong>Geochemistry, Geophysics, Geosystems
<p style="margin-left: 10px"><strong>volume: </strong>10
<p style="margin-left: 10px"><strong>title: </strong>Position of the Polar Front along the western Iberian margin during key cold episodes of the last 45 ka
</details>
<details style="margin-left: 10px">
<summary>pub2</summary>
</details>
</details>
<details open style="margin-left: 0px">
<summary>geo</summary>
<p style="margin-left: 0px"><strong>latitude: </strong>36.38
<p style="margin-left: 0px"><strong>longitude: </strong>-7.0717
<p style="margin-left: 0px"><strong>elevation: </strong>-577
<p style="margin-left: 0px"><strong>siteName: </strong>M39008_3
</details>
<details open>
<summary>PaleoData columns</summary>
<details style="margin-left: 10px">
<summary>depth (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_depth
<p style="margin-left: 10px"><strong>variableName: </strong>depth
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>Sample depth
</details>
<details style="margin-left: 10px">
<summary>ageDuplicate (cal years BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_age_median
<p style="margin-left: 10px"><strong>variableName: </strong>ageDuplicate
<p style="margin-left: 10px"><strong>units: </strong>cal years BP
<p style="margin-left: 10px"><strong>description: </strong>Median age
</details>
<details style="margin-left: 10px">
<summary>ageOriginal (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_age_original
<p style="margin-left: 10px"><strong>variableName: </strong>ageOriginal
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Original age
</details>
<details style="margin-left: 10px">
<summary>ageMedianBacon (cal years BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_age_medianMedianBacon
<p style="margin-left: 10px"><strong>variableName: </strong>ageMedianBacon
<p style="margin-left: 10px"><strong>units: </strong>cal years BP
<p style="margin-left: 10px"><strong>description: </strong>Median age
</details>
<details style="margin-left: 10px">
<summary>age (BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_age
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>BP
<p style="margin-left: 10px"><strong>description: </strong>Original age
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_uk37_SST_from_uk37
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST calculated from uk37
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variableGroup: </strong>Temperature
<p style="margin-left: 20px"><strong>variableGroupOriginal: </strong>T
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>seasonalityGeneral: </strong>annual
<p style="margin-left: 20px"><strong>seasonalityOriginal: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableGroupDirection: </strong>list("negative")
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>temperature (degC)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_d18o_bulloides_SST_from_d18o_bulloides
<p style="margin-left: 10px"><strong>variableName: </strong>temperature
<p style="margin-left: 10px"><strong>units: </strong>degC
<p style="margin-left: 10px"><strong>description: </strong>SST calculated from d18o_bulloides
<details>
<summary>interpretation</summary>
<details style="margin-left: 20px">
<summary>1</summary>
<p style="margin-left: 20px"><strong>direction: </strong>positive
<p style="margin-left: 20px"><strong>seasonality: </strong>annual
<p style="margin-left: 20px"><strong>variable: </strong>T
<p style="margin-left: 20px"><strong>seasonalityGeneral: </strong>annual
<p style="margin-left: 20px"><strong>scope: </strong>climate
<p style="margin-left: 20px"><strong>variableGroup: </strong>Temperature
<p style="margin-left: 20px"><strong>variableGroupOriginal: </strong>T
<p style="margin-left: 20px"><strong>seasonalityOriginal: </strong>1 2 3 4 5 6 7 8 9 10 11 12
<p style="margin-left: 20px"><strong>variableDetail: </strong>sea@surface
<p style="margin-left: 20px"><strong>variableGroupDirection: </strong>list("negative")
</details>
</details>
</details>
<details style="margin-left: 10px">
<summary>d18o_bulloides (per mil vs PDB)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_d18o_bulloides
<p style="margin-left: 10px"><strong>variableName: </strong>d18o_bulloides
<p style="margin-left: 10px"><strong>units: </strong>per mil vs PDB
</details>
<details style="margin-left: 10px">
<summary>Uk37 (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_uk37
<p style="margin-left: 10px"><strong>variableName: </strong>Uk37
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details>
<summary>ChronData columns</summary>
<details style="margin-left: 10px">
<summary>depth_top (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_depth_top
<p style="margin-left: 10px"><strong>variableName: </strong>depth_top
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>Sample top depth
</details>
<details style="margin-left: 10px">
<summary>depth_bottom (cm)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_depth_bottom
<p style="margin-left: 10px"><strong>variableName: </strong>depth_bottom
<p style="margin-left: 10px"><strong>units: </strong>cm
<p style="margin-left: 10px"><strong>description: </strong>Sample bottom depth
</details>
<details style="margin-left: 10px">
<summary>age_type (unitless)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>RrbI6wkb5aL
<p style="margin-left: 10px"><strong>variableName: </strong>age_type
<p style="margin-left: 10px"><strong>units: </strong>unitless
</details>
<details style="margin-left: 10px">
<summary>age (yr BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>R1mhLSiullR
<p style="margin-left: 10px"><strong>variableName: </strong>age
<p style="margin-left: 10px"><strong>units: </strong>yr BP
</details>
<details style="margin-left: 10px">
<summary>labcode ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_labcode
<p style="margin-left: 10px"><strong>variableName: </strong>labcode
<p style="margin-left: 10px"><strong>description: </strong>Lab sample code
</details>
<details style="margin-left: 10px">
<summary>mat_dated ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_mat_dated
<p style="margin-left: 10px"><strong>variableName: </strong>mat_dated
<p style="margin-left: 10px"><strong>description: </strong>Material dated
</details>
<details style="margin-left: 10px">
<summary>c14_date (RC yr BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_c14_date
<p style="margin-left: 10px"><strong>variableName: </strong>c14_date
<p style="margin-left: 10px"><strong>units: </strong>RC yr BP
<p style="margin-left: 10px"><strong>description: </strong>14C date
</details>
<details style="margin-left: 10px">
<summary>c14_1s_err (RC yr BP)</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_c14_1s_err
<p style="margin-left: 10px"><strong>variableName: </strong>c14_1s_err
<p style="margin-left: 10px"><strong>units: </strong>RC yr BP
<p style="margin-left: 10px"><strong>description: </strong>14C 1-sigma error
</details>
<details style="margin-left: 10px">
<summary>delta_r ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_delta_r
<p style="margin-left: 10px"><strong>variableName: </strong>delta_r
<p style="margin-left: 10px"><strong>description: </strong>delta R
</details>
<details style="margin-left: 10px">
<summary>delta_r_original ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_delta_r_original
<p style="margin-left: 10px"><strong>variableName: </strong>delta_r_original
<p style="margin-left: 10px"><strong>description: </strong>Original delta R
</details>
<details style="margin-left: 10px">
<summary>delta_r_1s_error ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_delta_r_1s_error
<p style="margin-left: 10px"><strong>variableName: </strong>delta_r_1s_error
<p style="margin-left: 10px"><strong>description: </strong>delta R 1-sigma error
</details>
<details style="margin-left: 10px">
<summary>delta_r_1s_error_original ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_delta_r_1s_error_original
<p style="margin-left: 10px"><strong>variableName: </strong>delta_r_1s_error_original
<p style="margin-left: 10px"><strong>description: </strong>Original delta R 1-sigma error
</details>
<details style="margin-left: 10px">
<summary>other_date ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_other_date
<p style="margin-left: 10px"><strong>variableName: </strong>other_date
<p style="margin-left: 10px"><strong>description: </strong>Other date
</details>
<details style="margin-left: 10px">
<summary>other_1s_err ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_other_1s_err
<p style="margin-left: 10px"><strong>variableName: </strong>other_1s_err
<p style="margin-left: 10px"><strong>description: </strong>Other date 1-sigma error
</details>
<details style="margin-left: 10px">
<summary>other_type ()</summary>
<p style="margin-left: 10px"><strong>TSid: </strong>T2L_M39008_3_other_type
<p style="margin-left: 10px"><strong>variableName: </strong>other_type
<p style="margin-left: 10px"><strong>description: </strong>Other date type
</details>

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Sitemap

```{r}
  map.meta.split <- split(map.meta, map.meta$archiveType)


factpal <- colorFactor("Paired",map.meta$archiveType)
buff <- 15
l <- leaflet() %>% 
  addTiles() %>% 
  fitBounds(map.meta$lon[i]-buff,map.meta$lat[i]-buff,map.meta$lon[i]+buff,map.meta$lat[i]+buff)
  

  
  
names(map.meta.split) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addMarkers(data=map.meta.split[[df]],
                 lng=~lon, lat=~lat,
                 label=~as.character(archiveType),
                 popup=~paste(str_c('Dataset: <a href="',link,'">',dataSetName,'</a>'),
                                 # str_c("Elevation: ",elev),
                                  str_c("Archive Type: ",archiveType),
                                  sep = "<br>"),
                 group = df,
                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
                 labelOptions = labelOptions(noHide = F,
                                             direction = 'auto'))
  })

l <- l %>%   addCircleMarkers(lng = map.meta$lon[i], lat = map.meta$lat[i],radius = 20,color = "red",fillColor = "none")

l %>%
  addLayersControl(position = "bottomleft",
    overlayGroups = names(map.meta.split),
    options = layersControlOptions(collapsed = FALSE,
                                   opacity = 0.8)
  )
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### temperature (degC)
```{r}
plotCol(thisTS,ind = 6)
```

### temperature (degC)
```{r}
plotCol(thisTS,ind = 7)
```

### d18o_bulloides (per mil vs PDB)
```{r}
plotCol(thisTS,ind = 4)
```

### Uk37 (unitless)
```{r}
plotCol(thisTS,ind = 5)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### depth_top (cm)
```{r}
plotCol(chronTS,ind = 2)
```

### depth_bottom (cm)
```{r}
plotCol(chronTS,ind = 3)
```
